# Generated by Django 3.2.4 on 2021-06-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
